### ISSUE TITLE
gettext API outdated

### ISSUE THREAD

**Issue by danikp** [erlydtl/erlydtl#200]
from dialyzer log
src/i18n/po_generator.erl:22: Call to missing or unexported function gettext_compile:open_po_file/3
src/i18n/po_generator.erl:24: Call to missing or unexported function gettext_compile:write_header/0
src/i18n/po_generator.erl:29: Call to missing or unexported function gettext_compile:close_file/0
src/i18n/po_generator.erl:37: Call to missing or unexported function gettext_compile:fmt_fileinfo/1
src/i18n/po_generator.erl:42: Call to missing or unexported function gettext_compile:write_pretty/1
src/i18n/po_generator.erl:54: Call to missing or unexported function gettext_compile:write_pretty/1

by looking at etnt/gettext some functions are really not exported or have different arity

**Comment by seriyps** [comment]
AFAIK, this file is not used now, so can be just dropped.

**Comment by kaos** [comment]
I think this was addressed by #201
