### ISSUE TITLE
relx can't build release with erlydtl, erlang 18

### ISSUE THREAD

**Issue by brigadier** [erlydtl/erlydtl#211]
relx can't build release with erlydtl, erlang 18
The error is
```
Failed to solve release:
 Dependency eunit_formatters is specified as a dependency but is not reachable by the system.
```
 eunit_formatters app must be manually included in the app.src file of the application which uses erlydtl to make it work.

**Comment by kaos** [comment]
Mm.. eunit_formatters should probably be moved to a test_deps section in the rebar config.

Maybe we could add relx release as a step in the tests.. as this is not the first issue with releases and erlydtl.

**Comment by unbalancedparentheses** [comment]
I am having the same issue. Please don't put eunit formatters as a dependency, add it as a test dep. If you want I can send a PR.

**Comment by kaos** [comment]
Yeah, that's the plan. PR welcome, otherwise I'll probably get around to it in the coming week.. :)
