### ISSUE TITLE
{% language %} tag is not supported

### ISSUE THREAD

**Issue by brigadier** [erlydtl/erlydtl#212]
Erlydtl does not support ```{% language "locale" %} ... {% endlanguage %}``` tag, which should replace locale in the arguments of the callback fun `translation_fun` for `trans` and `blocktrans` tags inside the tag. Also there's no error when this tag is used in the template, it just gets silently ignored.

And the second (lesser) issue - ```{% blocktrans trimmed %}``` is not supported as well. This form strips whitespace from content, which allows to have pretty formatting in both template and .po files.

**Comment by kaos** [comment]
Thanks. Will try and get some time to look into that.

**Comment by kaos** [comment]
@brigadier I've just pushed support for the `trimmed` option, but I haven't tested it yet. I want to write some test cases for the whole unparser and all the po stuff.. but since that may be a while, perhaps you can take a look, see if it seems to work in the mean time.. ;)

**Comment by seriyps** [comment]
I'm not absolutely sure, but looks like this implementation doesn't work very well with gettext server:

For example, we have template like

```
<html>
{%blocktrans trimmed%}
Hello world!
{%endblocktrans%}
</html>
```

It emit string `"Hello world!"` to .po file. But when this template will be rendered, it will query for a string `"\nHello world!\n"`. I mean, `translation_fun` will be called with not trimmed key string.

**Comment by kaos** [comment]
Hmm.. ok, right. Will take a look at that :)
