### ISSUE TITLE
no type casting in translations for blocktrans blocks with variables

### ISSUE THREAD

**Issue by brigadier** [erlydtl/erlydtl#213]
example
```
> {ok, Data} = erlydtl:compile_template("{% blocktrans %} test {{ n }} {% endblocktrans %}", test).
{ok,test}

> test:render([{n, 3}], [{translation_fun, fun(V, L) -> "translation {{ n }}" end}]).
{ok,[[<<"translation ">>,3,<<>>]]}
```

As you can see, `3` is inserted in the template as integer so it's just a character 0x3 instead of "3"

**Comment by seriyps** [comment]
https://github.com/erlydtl/erlydtl/blob/master/src/erlydtl_runtime.erl#L251 it's there

**Comment by brigadier** [comment]
yeah, already found this
something like this should fix this
```
interpolate_variables1(Tpl, Vars) ->
    %% pre-compile binary patterns?
    case binary:split(Tpl, <<"{{">>) of
        [Tpl]=NoVars -> NoVars; %% need to enclose in list due to list tail call below..
        [Pre, Post] ->
            case binary:split(Post, <<"}}">>) of
                [_] -> throw({no_close_var, Tpl});
                [Var, Post1] ->
                    Var1 = string:strip(binary_to_list(Var)),
                    Value = cast(orddict:fetch(Var1, Vars)),
                    [Pre, Value | interpolate_variables1(Post1, Vars)]
            end
    end.

cast(I) when is_integer(I) -> integer_to_list(I);
cast(F) when is_float(F) -> float_to_list(F);
cast(A) when is_atom(A) -> atom_to_list(A);
cast(A) -> A.


```

**Comment by kaos** [comment]
Or use `erlydtl_filters:format_number/1` https://github.com/erlydtl/erlydtl/blob/master/src/erlydtl_filters.erl#L371 and it'll work the same as in "normal" parts of the template.. (pull request welcome.. :)

**Comment by seriyps** [comment]
Ahh, looks like we also need to apply all this 'auto-escape' rules from https://github.com/erlydtl/erlydtl/blob/master/src/erlydtl_beam_compiler.erl#L1260
Should check how all this escaping stuff works with translations in Django...

**Comment by seriyps** [comment]
Yeah, in Django each blocktrans substitution variable is passed through function `render_value_in_context`:
https://github.com/django/django/blob/master/django/templatetags/i18n.py#L163-L165

Which apply all the escaping rules:
https://github.com/django/django/blob/master/django/template/base.py#L986

**Comment by seriyps** [comment]
So, template

```erlydtl
{% blocktrans %}
 My name is {{name}}
{% endblocktrans %}
```

With context

```erlang
[{name => "<script>alert('hack')</script>"}]
```

Should produce

```html
My name is &lt;script&gt;alert('hack')&lt;/script&gt;
```

**Comment by kaos** [comment]
:+1:

**Comment by brigadier** [comment]
what about this
```
cast(V) when is_integer(V); is_float(V) ->
    erlydtl_filters:format_number(V);
cast(V) when is_binary(V); is_list(V) ->
    erlydtl_filters:force_escape(V);
cast(V) ->
    erlydtl_filters:force_escape(io:format("~p", [V])).
```

**Comment by brigadier** [comment]
So it looks like we would need to have some context in the `translate_block` and `translate` functions. The state of autoescape and custom locale from the `{% language local %}` tag, which will be implemented earlier or later anyway.
