### ISSUE TITLE
compile_dir results in a module with broken translations

### ISSUE THREAD

**Issue by oxpa** [erlydtl/erlydtl#217]
Hello.

I use erlydtl in the following scenario:
```
erlydtl:compile_dir("templates/", web ).
case web:render(template1,
                    [ {prefix, <<"whatever">>} ],
                    [ {translation_fun, fun translate/2},
                      {locale, <<"ru-RU">> } ]) of
    {ok, Data} -> ?OK(Data);
    _ -> ?SERVER_ERROR
end;
```
No runtime translation occur, `translate` is never called.
But if I change the code and calls template function itself:
```
erlydtl:compile_dir("templates/", web ).
web:template1( [ {prefix, <<"whatever">>} ],
                          [ {translation_fun, fun translate/2}, {locale, <<"ru-RU">> } ]
             ).
    
```
everything works like a charm (aside from the fact, I don't control rendering).
Compile time translations work.
Additionally, there is no 'translated_blocks' function at all in `web` module.

Could you please have a look? I failed even adding a test ;)

**Comment by kaos** [comment]
Thanks for the report. I'll take a closer look..

**Comment by kaos** [comment]
@oxpa I've added four functions that were missing when compiling a directory template module that exists when you compile file by file. Looking at the compiled code, it doesn't make sense that translations would work when you call `web:template1/2` but not when you call `web:render/3`. Maybe it's the code that's doing the rendering that did the wrong thing based on the fact that `translated_blocks/0` were missing.. ?

Could you retest with the fix applied and see if it's still an issue?

Note to self: would still be nice with some more tests on dir compiled modules.

**Comment by kaos** [comment]
I'll close this for now. Please open a new issue if there still are any unresolved issues.
