### ISSUE TITLE
localization problems

### ISSUE THREAD

**Issue by oxpa** [erlydtl/erlydtl#218]
This is not really an issue, it's more of a query ;)
 
You may notice, there are more `date` filter keys in django than in erlydtl. I'm especially interested in that "E" which produces alternative localized month name.
You may notice, that django uses translation system to produce them: https://github.com/django/django/blob/8047e3666b0b50bb04e6f16c2a4fb21ddfd5713f/django/utils/dates.py#17

How do you think, is it a good idea to introduce `translation_fun` usage for months names? It would solve several minor issues I have with my templates but I can't say if those are common.

The problem I'm trying to solve can be described with following short template:
```{{_(myDate|date:"F")}}``` produces wrong translation for me: nor can pass any context with month name, nor can I use hardcoded month name.
Support for localized dates, for translation function in the filter code, would allow me to use simply this:
```{{myDate|date:"F"}}``` for a simple name and
```{{myDate|date:"E"}}``` for alternative name.

Abbreviations could be rewritten too.

So, the questions:
Does anyone have this implementation?
Does it worth implementing?
Would you accept a date filter patch with translation_fun invocations?

**Comment by kaos** [comment]
I don't know of anyone have this implemented already. It's definitely worth implementing.

I'd interested to see how you'd go about implementing this using the `translation_fun`. If it looks good, sure I'll merge it. If you go down that route, feel free to open a pull request for review and feedback as you go along (no need to wait until you are "done"), to get early feedback.

**Comment by oxpa** [comment]
@kaos please, have a look at #219 .

**Comment by kaos** [comment]
fixed by #219
