### ISSUE TITLE
Fail to render a DTL where a block is to be expanded twice?

### ISSUE THREAD

**Issue by aherranz** [erlydtl/erlydtl#220]
Hi everyone, I am using ChicagoBoss and in the upgrade from 0.9.4 to 0.10.0 we have detected that our code fail to render a DTL where a block is to be expanded twice: https://github.com/ChicagoBoss/ChicagoBoss/issues/615

We think the problem is in ErlyDTL but we are users of CB with no knowledge on ErlyDTL so it is diffcult to check if the problem is in ErlyDTL or even if it is a bug or a feature. This is the code that raise an error: a base DTL, let's say `admin/layouts/admin.html`, with a block expanded in two different points:

```html
<head>
  <title>Chicago Boss Admin - {% block title %}{% endblock %}</title>
</head>
<body>
  <h1>Chicago Boss Admin - {% block title %}{% endblock %}</h1>
</body>
```

And a DTL that expands the previous one:

```html
{% extends "admin/layouts/admin.html" %}
{% block title %}General Info{% endblock %}
```

This code works smoothly with 0.9.4 .

Kind regards.

**Comment by kaos** [comment]
Nice catch @aherranz , thank you.

**Comment by aherranz** [comment]
Great. Thanks!
