### ISSUE TITLE
erlang 18.1  syntax_tools / merl

### ISSUE THREAD

**Issue by crownedgrouse** [erlydtl/erlydtl#221]
Hi,
While upgrading to 18.1 , my project fails to build due to conflict merl module between syntax_tools and merl. But using only syntax_tools as dependencies fails with {undef,[{compile,forms,[[{attribute,485,module,template_name} ;
Any tip ?

**Comment by crownedgrouse** [comment]
https://github.com/erlang/otp/commit/c12d2dc802df9510ae32ac37ccefeb162767774c

**Comment by kaos** [comment]
which version of erlydtl are you using?

There's been a couple commits (b992c452c1d61adbc871d6d7df8a3c9236bf7444, f8602ca664115d4fe07bcd60a31ae212b07933d0) to master that address this, but haven't made a release of it yet..

**Comment by crownedgrouse** [comment]
Hi, The one in Erlang.mk as simple dependancy.

**Comment by crownedgrouse** [comment]
Looks like it is master in Erlang.mk index

**Comment by crownedgrouse** [comment]
hi, by compiling erlydtl with rebar in deps/erlydtl  before my make, it is working. I suppose erlang.mk does not work with your hack testing the erlang version.

**Comment by crownedgrouse** [comment]
confirmed. by removing deps/erlydtl/ebin/* and using make, the application fail to start in my release. I suppose it is related to erlydtl/src/erlydtl.app.src.script . I open an issue to Loïc 's github.
