### ISSUE TITLE
how to define my template keyword like "session"

### ISSUE THREAD

**Issue by wuchuguang** [erlydtl/erlydtl#222]
user-define "session"
i want to use like this:
{% session get account_name %}
{% session set account_name "my_name" %}
or other way use it

**Comment by kaos** [comment]
You register your own library module (as behaviour module, implementing the erlydtl_library behaviour), registering a `session` tag.
See these files to get started:
https://github.com/erlydtl/erlydtl#custom-tags-and-filters
https://github.com/erlydtl/erlydtl/blob/master/src/erlydtl_library.erl
https://github.com/erlydtl/erlydtl/blob/master/test/erlydtl_lib_test1.erl
https://github.com/erlydtl/erlydtl/blob/master/test/erlydtl_custom_tags_lib.erl

I realize the docs need a few examples on this topic.

**Comment by wuchuguang** [comment]
i define session.erl (filter session)
code:
-module(tag_session).
-behaviour(erlydtl_library).

%% API
-export([inventory/1, version/0]).

-export([hello/1]).

inventory(filters) ->
    [hello];
inventory(tags) -> [].

version() ->1.


hello(Str) when is_list(Str)->
    Str++" hello";
hello(Bin) when is_binary(Bin) ->
    "dddddddddddddd".

use like this :
    {{ wwww | session:100 }}

but template generate beam ,then decode erl 
 not find about session code

**Comment by wuchuguang** [comment]
session:inventory(filters) session:inventory(tags)
not call in complite_template or xxx:render([{wwww, "aaaaaaa"}]).

**Comment by wuchuguang** [comment]
i use session this filter (or tag) , but session module not called,

**Comment by kaos** [comment]
do you pass `default_libraries` to the compile options when compiling your template?
Something like: `erlydtl:compile("template", mod, [{default_libraries, tag_session}]).`
You must also make sure that the `tag_session` module has been compiled with `erlc`, naturally.

**Comment by wuchuguang** [comment]
it ok. thank you very much.

**Comment by wuchuguang** [comment]
no no, i see erorr.

**Comment by wuchuguang** [comment]
-export([render/0, render/1, render/2, source/0, dependencies/0, translatable_strings/0,
	 translated_blocks/0, variables/0, default_variables/0, constants/0]).

source() -> {"../welcome_template.txt", "[Lw��)��zB\"?�<=�"}.

dependencies() -> [].

variables() -> [wwww].

default_variables() -> [].

constants() -> [].

translatable_strings() -> [].

translated_blocks() -> [].

render() -> render([], []).

render(Variables) -> render(Variables, []).

render(Variables, RenderOptions) ->
    try render_internal(Variables, RenderOptions) of Val -> {ok, Val} catch Err -> {error, Err} end.

render_internal(_Variables, RenderOptions) ->
    _TranslationFun = erlydtl_runtime:init_translation(proplists:get_value(translation_fun,
									   RenderOptions, none)),
    _CurrentLocale = proplists:get_value(locale, RenderOptions, default),
    _RecordInfo = [],
    erlydtl_runtime:stringify_final([erlydtl_filters:format_number(erlydtl_filters:force_escape([])),
				     <<10, 97, 97, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 10, 10, 10>>],
				    true).

**Comment by wuchuguang** [comment]
not find session code

**Comment by wuchuguang** [comment]
session:verion() has be called, but generate code not find about something session

**Comment by wuchuguang** [comment]
template : {{ wwww|session }}

**Comment by wuchuguang** [comment]
template:render([{wwww, "aaaaaaa"}]).

**Comment by wuchuguang** [comment]
{error_info,
                                                                                   false,
                                                                                   false,
                                                                                   [{"../welcome_template.txt",
                                                                                     [{{1,
                                                                                        9},
                                                                                       erlydtl_beam_compiler,
                                                                                       {unknown_filter,
                                                                                        session,
                                                                                        1}}]},
                                                                                    {"../welcome_template.txt",
                                                                                     [{none,
                                                                                       erlydtl_compiler_utils,
                                                                                       {load_library,
                                                                                        session,
                                                                                        session,
                                                                                        {version,
                                                                                         4}}}]}]}

**Comment by wuchuguang** [comment]
compile :   #dtl_context.filters  not session (filter)

**Comment by wuchuguang** [comment]
success .
session.erl
-erlydtl_library(erlydtl_libary) 
session is a library .
inventory(tags) ->[xxx,xxx] lib has define xxx, xxx tags
inventory(filters) ->[xxx,xxx] lib has define xxx xxx filters

**Comment by kaos** [comment]
OK, I take it you got it to work. If not, feel free to open a new issue :)
