### ISSUE TITLE
Dialyzer error on erlydtl_compiler, line 429

### ISSUE THREAD

**Issue by mhishami** [erlydtl/erlydtl#223]
Hi,

I got this error when dialyzing my app:
```
erlydtl_compiler.erl:429: Call to missing or unexported function erlydtl_parser:resume/1
```
Function erlydtl_parser:resume/1 is no longer there as I have checked.

line 422-429:
```
        {error, ExtErr, ExtState} ->
            case reset_parse_state(ExtState, Context) of
                {_, []} ->
                    %% todo: see if this is indeed a sensible ext error,
                    %% or if we should rather present the original Err message
                    {error, ExtErr};
                {State2, ExtParsed} ->
                    check_parse(erlydtl_parser:resume(State2), Acc ++ Parsed ++ ExtParsed, Context)
            end;
```

**Comment by kaos** [comment]
I've looked into it, and I conclude that it has to be something in your build that is off. I don't get this error locally, nor does the tests on Travis: https://travis-ci.org/erlydtl/erlydtl/jobs/86060428#L203

The `resume/1` function is exported by https://github.com/erlydtl/erlydtl/blob/master/include/erlydtl_preparser.hrl

So, if you don't get that version of the header in `erlydtl_parser.erl`, then your includes are borked.

**Comment by kaos** [comment]
Ah, and please feel free to re-open in case you find something that still needs to be addressed on this..
