### ISSUE TITLE
Failed to extract name from erlydtl.app.src

### ISSUE THREAD

**Issue by houdelou** [erlydtl/erlydtl#231]
Hello,

I have the following error when compiling on Windows. Using stable branch of erlydtl and master branch of rebar.

NOTICE: Using experimental *.app.src.script functionality on erlydtl.app.src
ERROR: failed to extract name from erlydtl.app.src: {unexected_terms, ...

If I remove the .script file, it works. The problem is when using rebar get-deps, it automatically uses the .script.

**Comment by kaos** [comment]
Thanks for the report.

I currently don't have a Windows machine to test on, so won't be able to fix without a bit of help, or a PR would be handy. ;)

Do you have the full error message you get?

**Comment by houdelou** [comment]
Yes sure,

First message I get:

```
process_begin: CreateProcess(NULL, env escript erlydtl\
rebar get-deps, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:15: recipe for target 'get-deps' failed
make: *** [get-deps] Error 2
```

I found two solutions to this problem:

# 1) Compile a new rebar for Windows and put it in my PATH and Change REBAR=./rebar $(REBAR_ARGS) to REBAR=escript rebar $(REBAR_ARGS) to take the new rebar.

```
NOTICE: Using experimental *.app.src.script functionality on erlydtl/src/erlydtl.app.src
ERROR: Failed to extract name from erlydtl/src/erlydtl.
app.src: {unexpected_terms,

          {ok,

           {application,

            erlydtl,

            [{description,

              "Django Template Language for Erlang"},

             {vsn,

              git},
             {modules,

              []},

             {applications,

              [kernel,

               stdlib,

               compiler,

               syntax_tools,

               merl]},

             {registered,

              []}]}}}
Makefile:15: recipe for target 'get-deps' failed
make: *** [get-deps] Error 1
```

Then, I remove erlydtl.app.src.script and it works.

# 2) Second option is shorter :) Change REBAR=./rebar $(REBAR_ARGS) to REBAR=escript ./rebar $(REBAR_ARGS).

**Comment by kaos** [comment]
Thanks, will see what I can come up with. Don't hold your breath, though ;)

**Comment by houdelou** [comment]
lol, ok. Anyway, I got it working. I really should think about switching to Linux for Erlang dev because it seems to be really more compatible. Thanks

**Comment by binarytemple** [comment]
Same issue here with Erlang 19, OS X. If I use my local copy of rebar it works:

```
% rebar --version
rebar 2.6.2 18 20160728_232250 git 2.6.2-4-g0c6326c
```

**Comment by 64bit** [comment]
https://github.com/erlydtl/erlydtl/pull/254  works, I ran into same issue and changed code similar to pull request, it works fine, please merge it.

**Comment by kaos** [comment]
Apologies for my long absence.
