### ISSUE TITLE
Link to Django 1.6 docs in README is broken

### ISSUE THREAD

**Issue by jonathanperret** [erlydtl/erlydtl#235]
https://github.com/erlydtl/erlydtl/blob/f81b7be/README.markdown links to http://docs.djangoproject.com/en/1.6/ref/templates/builtins/ which now returns a 404. It appears the Django project removes the docs for old versions of Django.

https://docs.djangoproject.com/en/stable/ref/templates/builtins/ appears to be a permalink, but it may not be a good idea to link to the latest version if the Django syntax evolves.

The oldest reference still online is that for 1.7: https://docs.djangoproject.com/en/1.7/ref/templates/builtins/ . Because I'm just starting out with erlydtl and have no Django experience, I have no idea whether that one is still relevant. That's basically why this is an issue and not a PR!

**Comment by kaos** [comment]
Thanks for the heads up. Will look into it. (I'm no django veteran either, fwiw).
