### ISSUE TITLE
How to get the {ok, iolist()} from compile_dir?

### ISSUE THREAD

**Issue by drozzy** [erlydtl/erlydtl#236]
I don't really understand what this means:

> Notice: The exported template functions return an iolist() on success only, failures are non-local (e.g. as a throw). To get the result in wrapped tuple {ok, iolist()} | {error, Reason} call one of the render functions: render(Tag) | render(Tag, Vars) | render(Tag, Vars, Opts).

Here is how I currently get my template rendered when using `compile_dir`:

`erlydtl:compile_dir(template:path(), dtl, [{out_dir, "."}])`

here is the template:

`	Body = dtl:index([])`

Where would I call "render" here and what is a tag?

Thank you.

**Comment by kaos** [comment]
Tag is the entry function you normally call, like `index`. So I think in your case, it would be:
```
{ok, Body} = dtl:render(index, []).
```

Internally, in the compiled helper module, I think it simply does something like this:
```
index(Vars) ->
  {ok, Result} = render(index, Vars),
  Result.

%% etc...
```

**Comment by drozzy** [comment]
Thanks.
