### ISSUE TITLE
How to create a custom tag?

### ISSUE THREAD

**Issue by drozzy** [erlydtl/erlydtl#238]
"Starting with release 0.9.1, the recommended way to add custom tags and filters are to register a module"

How does one register a module with erlydtl?

P.S.: Created a stackoverflow tag: http://stackoverflow.com/questions/tagged/erlydtl
Will ask future questions there :-)

**Comment by kaos** [comment]
Sorry for the belated response.

I realize the docs could use some more examples. It's the options that refers to `library` you want:
```
libraries - A list of {Name, Module} libraries implementing custom tags and filters. Module should implement the erlydtl_library behaviour (see [Custom tags and filters] below).
```
and
```
default_libraries - A list of libraries that should be loaded by default when compiling a template. Libraries can be specified either by name (when there is a name to module mapping also provided in the libraries option) or by module.
```

If you register a library, but doesn't load it by default, you can load it from a template with the `{% load libname %}` tag.
