### ISSUE TITLE
custom tags parameters parsing not handling newlines

### ISSUE THREAD

**Issue by mpenet** [erlydtl/erlydtl#240]
I had a tag call like the following but with a lot more parameters, so I ended up using a similar formating with new lines between parameters. However this is rejected/misinterpreted by the parser. It would be nice if it could handle this.

```django
 {% foo param1="bar" 
        param2="baz" %}
```

**Comment by kaos** [comment]
Thanks for the report. I'm out traveling, but will have a look once I get back home (in a few days).

**Comment by kaos** [comment]
@mpenet thanks for catching that. It was easy enough to fix (adding three lines: https://github.com/erlydtl/erlydtl/commit/ea9f0dd723393037c5290bd1b809e6496a4fe00c#diff-dfcc00b7869893a3136f2645764a3c88R220 )
