### ISSUE TITLE
Support for 19

### ISSUE THREAD

**Issue by kostis** [erlydtl/erlydtl#242]
Please also add `19` in the `rebar.config` script.

PS. I would have created a pull request for it, but it seems quite trivial a change.

**Comment by kaos** [comment]
Thanks Kostis.

There's so little activity here on the github issues for erlydtl, so I wonder if it is used at all (I have a hard time believing there are no issues with it ;)

**Comment by benbro** [comment]
Can you please make a point release for this r19 fix?

**Comment by kostis** [comment]
We are using/relying on erlydtl for [nifty](https://github.com/parapluu/nifty). For what's worth, we have not found any issues with it.

By the way, I would like to second @benbro's suggestion.  Code bases wanting to migrate (or support) Erlang/OTP 19.0 cannot use the latest tagged version of erlydtl and many projects I know are reluctant to depend on the HEAD of github repositories.  Thanks for your work!

**Comment by kaos** [comment]
Thanks, and sorry for the long wait. I've finally made a 0.12.0 release with the latest fixes (and switched branching model to make it easier on my head, keeping it aligned with what we use at work, and updated the makefile to make it easier to do releases in the future..)

**Comment by benbro** [comment]
Thanks
