### ISSUE TITLE
filters in {{ _(var) }} construction

### ISSUE THREAD

**Issue by brigadier** [erlydtl/erlydtl#248]
It would be nice to be able to use filters in `{{ _(var) }}` construction.
Such as for example `{{ _(message)|escapejs }}`.
As far as I know Django allows using filters in _(), but it does not allow vars, only constants in _(). Erlydtl allows both vars and constants, but not filters.

**Comment by seriyps** [comment]
+1, also miss this feature.

Particularly, I need to escape quotes in constructions like

```
<textarea placeholder="{% trans  'My placeholder, containing "dquote" in text' | escape %}">
<textarea placeholder="{{  _('My placeholder, containing "dquote" in text') | escape }}">
```

Or like that.

When I last checked (2-3 month ago), Django doesn't support this kind of syntax. But this doesn't mean we can't.

**Comment by brigadier** [comment]
Django does support it - https://groups.google.com/forum/#!topic/django-users/VSMP4jq2zU4

**Comment by kaos** [comment]
@brigadier let me know how it works :)

**Comment by brigadier** [comment]
Looks like it does not work well.
At the moment with the syntax `{{ _(var|filter) }}` it takes a string, applies a filter, then looks for the translation of the result. Correct syntax would be `{{ _(var)|filter }}` - with semantics "take a string, translate it, escape the result".

**Comment by kaos** [comment]
> Correct syntax would be `{{ _(var)|filter }}`

Indeed, and this is what I have in the tests.. so I'm not sure I understand your issue in the previous comment.

**Comment by brigadier** [comment]
I thought this change was already in master branch. Checked out develop, it works as it is supposed to. Thank you!
