### ISSUE TITLE
Push release to hex.pm

### ISSUE THREAD

**Issue by fenollp** [erlydtl/erlydtl#249]
Now that https://github.com/erlydtl/erlydtl/tree/0.12.0 is out, could it be possible for https://hex.pm/packages/erlydtl to also display the latest version?

**Comment by kaos** [comment]
@Licenser what needs to be done for this?

**Comment by fenollp** [comment]
This helped me: https://hex.pm/docs/rebar3_publish

**Comment by kaos** [comment]
Ok, I'll have a look. But it may take a few days.. PR's welcome if you're in a hurry ;)

**Comment by kaos** [comment]
@Licenser I now have registered as @kaos on hex.pm, in case you'd like to add me as maintainer there (I get a 403 when I try to publish now..)

**Comment by Licenser** [comment]
Would love to, but I need your e-mail address to sign the package over :)

**Comment by kaos** [comment]
Published to hex.pm: https://hex.pm/packages/erlydtl/0.12.0

**Comment by fenollp** [comment]
Thanks!
