### ISSUE TITLE
Support nesting templates

### ISSUE THREAD

**Issue by Kvaz1r** [erlydtl/erlydtl#253]
I not found any example or note about this, so is 'erlydtl' have support nesting templates?

**Comment by kaos** [comment]
Yes, it does.

There is the `extends` keyword, as well as `include`.

See the tests for example usage, https://github.com/erlydtl/erlydtl/blob/master/test/files/input/extends_path2 and friends.

and the django docs for more info.

**Comment by Kvaz1r** [comment]
Thanks I'll trying example for django templates.
