### ISSUE TITLE
Warnings about get_stacktrace()

### ISSUE THREAD

**Issue by Taure** [erlydtl/erlydtl#265]
I am using a later version of Erlang 21+ and I get warnings about get_stacktrace() will be depricated. We use 0.12.1 in our framework. https://github.com/novaframework/nova

Not sure how this can be handled to also support older version of Erlang.

**Comment by seriyps** [comment]
See https://github.com/erlydtl/erlydtl/pull/266#issuecomment-523833211

**Comment by Taure** [comment]
We can close this as it have been resolved. Is it possible to create a new tag and release a hex package with fix in #266?

**Comment by seriyps** [comment]
I can push a new tag (and update app.src), but I don't have hex.pm access. Should ping @Licenser or @kaos for that.

**Comment by grantwinney** [comment]
It'd be great to have this available on hex.pm when someone has the time. 😁🤞 (Fix was https://github.com/erlydtl/erlydtl/pull/267)

**Comment by kaos** [comment]
Sorry about the delay. @seriyps  is now owner of erlydtl at hex.pm.

**Comment by seriyps** [comment]
Thanks @kaos. I published 0.13.1

**Comment by kaos** [comment]
Awesome 👍🏽
